### ISSUE TITLE
Framework throws exception when run with no arguments

### ISSUE THREAD

**Issue by ChandlerSwift** [UMDLARS/CYLGame#38]
```
chandler@helium:~/projects/breakout$ pipenv run python game.py
Traceback (most recent call last):
  File "game.py", line 482, in <module>
    run(Breakout)
  File "/home/chandler/projects/breakout/CYLGame/Game.py", line 411, in run
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by ChandlerSwift** [comment]
https://stackoverflow.com/a/54161510
https://bugs.python.org/issue16308
https://stackoverflow.com/questions/23349349/argparse-with-required-subparser/23354355#23354355
